<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UserSecretsId>c2e564ce-e670-4b81-8cf5-c324be289937</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="GovukNotify" Version="7.2.0" />
    <PackageReference Include="GovUK.Dfe.CoreLibs.Security" Version="1.1.28" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.7" />
	<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.8.4" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-rvv3-g6hj-g44x" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dfe.Complete.Application\Dfe.Complete.Application.csproj" />
    <ProjectReference Include="..\Dfe.Complete.Domain\Dfe.Complete.Domain.csproj" />
  </ItemGroup>

</Project>
